### PR TITLE
Add multiple currencies and pending transactions

### LINKED ISSUE #76: Show unconfirmed transactions in a "pending" state
[Data available here](https://www.blockcypher.com/dev/ethereum/#unconfirmed-transactions-endpoint).

### PR DESCRIPTION
**Pull request by dan1elhughes**
### Description

Adds the following features:

- Abstract API base class which is extended by the APIs: `pending` (get pending transactions), `tokenMetadata` (get decimals/name for a token), `txHash` (get amounts and timestamps for a transaction) and `transactions` (get completed transactions). There are a number of APIs because many data sources have to be combined to get the full picture.
- Multiple currency support. Currencies can be added through repeat `store.dispatch(addToken(address))` calls.
- Pending transaction support. Polls an external API and uses Etherscan to convert the resulting hashes to contract data.
- Changes NumberInput to take a number as a value.
- Caches identity resolver responses to prevent requesting identities many times
- Updates DailyTotal to calculate total from each token taking decimals into account
- Adds trust and token metadata to the transactionslist container
- Moves isFSA out of actions and into the reducer builder to decrease code noise
- Splits updateSettings action into multiple actions, one for each relevant item of data stored

### Issues fixed

Fixes #76.

### Checklist

- [x] `npm test` returns no warnings or errors.

### CODE REVIEW

**Comment by dan1elhughes** [comment]
Unit tests to be updated

**Comment by ShaunBulbrook** [comment]
I'm happy with the changes. - But the tests are failing. 😭 

Can you take a look when you can. - Would be awesome to get this in before Friday. - Let me know if anyone else can take a look in the interim.

**Comment by peasandwell** [comment]
I can have a look at the tests

**Comment by peasandwell** [comment]
Updated test scripts for the transaction reducer are IN 🙌

**Comment by dan1elhughes** [comment]
Rebased onto master

**Pull request merged**
